<?php
// $Id$

/**
 * @file
 * Small improvements designed to enhance the default features used in Drupal Gardens.
 */

/**
 * Implements hook_media_browser_plugins_alter().
 */
function gardens_features_required_media_browser_plugins_alter(&$plugins) {
  // The remote_file plugin provided by the Remote Stream Wrapper module has not
  // yet been sufficiently tested for Drupal Gardens.
  unset($plugins['remote_file']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gardens_features_required_remote_stream_wrapper_media_browser_form_alter(&$form) {
  // hook_media_browser_plugins_alter() runs after
  // hook_media_browser_plugin_view(), so doesn't prevent all possible hijack
  // mechanisms. Therefore, also strip away form access.
  $form['#access'] = FALSE;
}
